# -*- coding: utf-8 -*-
"""DataVisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UDGI-aY6xdykKk-KbxV2ZFfQPAcXtaH

**Read data**
"""

import pandas as pd
import os
import glob
from google.colab import drive
# 1. Kết nối Google Drive
drive.mount('/content/drive', force_remount=True)
# ----------------------------------------------------
data_folder_path = '/content/drive/My Drive/cleaned/'
# Khởi tạo một dictionary rỗng để chứa dữ liệu
stock_data = {}

# Tự động tìm tất cả các file .csv trong thư mục
all_csv_files = glob.glob(os.path.join(data_folder_path, "*.csv"))

if not all_csv_files:
    print(f"LỖI: Không tìm thấy file .csv nào trong: {data_folder_path}")
else:
    print(f"Tìm thấy {len(all_csv_files)} file. Bắt đầu đọc...")

    for file_path in all_csv_files:
        try:
            # Lấy tên file (ví dụ: 'HVN.csv') từ đường dẫn
            file_name = os.path.basename(file_path)
            # Lấy ticker (ví dụ: 'HVN') từ tên file (bỏ đuôi .csv)
            ticker = os.path.splitext(file_name)[0]

            if ticker == "All":
              continue

            # Đọc file CSV
            df = pd.read_csv(file_path, parse_dates=['Date'], index_col='Date')

            # Lưu DataFrame vào dictionary với key là ticker
            stock_data[ticker] = df

            print(f"  Đã đọc {file_name:10} -> lưu vào stock_data['{ticker}']")

        except Exception as e:
            print(f"Lỗi khi đọc file {file_path}: {e}")

# --- Hướng dẫn sử dụng ---
print("\n================================================")
print("ĐỌC DỮ LIỆU VÀO DICTIONARY THÀNH CÔNG!")
print("================================================\n")
print("Để xem 5 dòng đầu của mã HVN, bạn dùng:")
print("stock_data['HVN'].head()")

# Bỏ bình luận (uncomment) dòng dưới để chạy thử:
if 'HVN' in stock_data:
    print(stock_data['HVN'].head())
else:
    print("\nKhông tìm thấy ticker 'HVN' trong dữ liệu, hãy kiểm tra lại tên file.")

# Gộp tất cả các DataFrame trong dictionary lại thành 1 DataFrame duy nhất
try:
    combined_df = pd.concat(stock_data.values())

    # Sắp xếp lại toàn bộ DataFrame theo ngày (index)
    combined_df.sort_index(inplace=True)

    print("Đã tạo combined_df thành công!")
    print(combined_df.head())
    print(combined_df['Ticker'].unique())
except Exception as e:
    print(f"Lỗi khi gộp dictionary: {e}")

# Cài đặt thư viện (nếu cần)
# !pip install plotly seaborn
# !pip install -U kaleido


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# Cài đặt theme mặc định cho seaborn
sns.set_theme(style="whitegrid")

# Giả sử các mã cổ phiếu của bạn là:
tickers = sorted(combined_df['Ticker'].unique())

# Chọn bảng màu Set2
palette = px.colors.qualitative.Set2

# Tạo map giữa Ticker và màu
color_map = {ticker: palette[i % len(palette)] for i, ticker in enumerate(tickers)}

from google.colab import files

import plotly.express as px
import plotly.io as pio

print(pio.kaleido.scope)

print("--- 1. Bắt đầu vẽ Biểu đồ đường (Giá đóng cửa) cho 7 mã ---")

# Giả sử 'stock_data' là dictionary chứa { 'MÃ': DataFrame }
# Trong đó mỗi DataFrame có cột 'Close' và index là ngày (DatetimeIndex)

for ticker, df in stock_data.items():

    # Dùng plotly.express để vẽ
    fig = px.line(
        df,
        x=df.index,
        y='Close',
        # title=f"Biểu đồ giá đóng cửa của mã {ticker}",
        labels={
            "index": "Ngày giao dịch",
            "Close": "Giá đóng cửa (VND)"
        }
    )

    # Cập nhật bố cục (layout)
    fig.update_layout(
        title={
            # 'text': f"📈 Biểu đồ giá đóng cửa của mã {ticker}",
            'y':0.97,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'
        },
        font=dict(family="Arial", size=14),
        xaxis_title="Ngày giao dịch",
        yaxis_title="Giá đóng cửa (VND)",  # có thể đổi sang USD nếu cần
        legend_title_text="Chú thích",
        plot_bgcolor="white"
    )

    # Cập nhật màu và đường kẻ
    fig.update_yaxes(
        tickformat=",.0f",          # Hiển thị 120000 → 120,000
        showgrid=True,
        gridwidth=0.5,
        gridcolor="LightGray"
    )

    fig.update_xaxes(
        title_text="Ngày",
        tickformat="%Y-%m",        # hiển thị 2024-04 thay vì Apr 2024
        showgrid=True,
        gridwidth=0.5,
        gridcolor="LightGray"
    )
    # Hiển thị biểu đồ
    fig.show()

    # Xuất file ảnh PNG
    filename = f"{ticker}_close_chart.png"
    fig.write_image(filename, scale = 3)
    files.download(filename)
    print(f"✅ Đã lưu: {filename}")

print("--- 🎉 Hoàn thành 7 biểu đồ đường ---")

print("\n--- 2. Bắt đầu vẽ Biểu đồ cột (So sánh Khối lượng TB) ---")

# 1. Tạo một dictionary để lưu khối lượng trung bình
average_volumes = {}

# Lặp qua các mã để tính giá trị trung bình
for ticker, df in stock_data.items():
    average_volumes[ticker] = df['Volume'].mean()

# 2. Chuyển dictionary vừa tạo thành DataFrame để vẽ
avg_vol_df = pd.DataFrame(average_volumes.items(),
                          columns=['Ticker', 'AverageVolume'])

# 3. Sắp xếp để biểu đồ dễ nhìn hơn (tùy chọn)
avg_vol_df = avg_vol_df.sort_values(by='AverageVolume', ascending=False)

# 4. Vẽ biểu đồ cột bằng Plotly
fig_bar = px.bar(
    avg_vol_df,
    x='Ticker',
    y='AverageVolume',
    color='Ticker',  # thêm màu khác nhau cho từng mã
    # color_discrete_sequence=px.colors.qualitative.Set2,  # bộ màu nhẹ
    color_discrete_map=color_map
)

fig_bar.update_traces(
    texttemplate='%{y:,.0f}',
    textposition='outside'
)

fig_bar.update_layout(
    title={
        # 'text': "So sánh Khối lượng Giao dịch Trung bình các Mã Cổ phiếu",
        'y': 0.92,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': dict(size=20, family='Arial', color='black')
    },
    xaxis_title='Mã Cổ phiếu',
    yaxis_title='Khối lượng trung bình (cổ phiếu)',
    font=dict(family="Arial", size=14, color="black"),
    plot_bgcolor='white',
    paper_bgcolor='white',
)
fig_bar.show()

fig_bar.update_xaxes(
    mirror=True,
    showgrid=True,
    gridwidth=1,
    gridcolor='lightgray'
)
fig_bar.update_yaxes(
    mirror=True,
    showgrid=True,
    gridwidth=1,
    gridcolor='lightgray'
)

filename123 = f"AverageVolumn.png"
fig_bar.write_image(filename123)
files.download(filename123)

print("--- Hoàn thành 1 biểu đồ cột so sánh ---")

print("\n--- 3. Bắt đầu vẽ Biểu đồ nhiệt (Heatmap) cho 7 mã ---")

# Các cột bạn muốn phân tích tương quan
columns_to_correlate = ['Open', 'High', 'Low', 'Close', 'Volume']

for ticker, df in stock_data.items():

    # 1. Lọc ra DataFrame con chỉ chứa 5 cột cần thiết
    df_subset = df[columns_to_correlate]

    # 2. Tính ma trận tương quan
    corr_matrix = df_subset.corr()

    # 3. Vẽ Heatmap bằng Seaborn
    # (plt.figure) tạo một khung hình mới cho mỗi biểu đồ
    plt.figure(figsize=(8, 6))

    sns.heatmap(corr_matrix,
                annot=True,     # Hiển thị số (giá trị tương quan)
                cmap='coolwarm',# Dùng thang màu Xanh-Đỏ
                fmt='.2f',      # Định dạng số (2 chữ số thập phân)
                linewidths=.5)

    plt.title(f'Ma trận tương quan (O-H-L-C-Vol) của mã: {ticker}')

    # (plt.show) hiển thị biểu đồ vừa vẽ
    plt.show()

print("--- Hoàn thành 7 biểu đồ nhiệt ---")

import numpy as np
import plotly.express as px
from google.colab import files

print("--- 1. Bắt đầu vẽ Biểu đồ Lợi nhuận Tích lũy ---")

# 1. Tính lợi nhuận tích lũy cho mỗi mã
df_cum = combined_df.reset_index()

# Tính LogReturn tích lũy
df_cum['CumulativeLogReturn'] = df_cum.groupby('Ticker')['LogReturn'].cumsum()

# 2. Đổi Log Return → Return tích lũy (giá trị nếu đầu tư 1đ ban đầu)
df_cum['CumulativeReturn'] = df_cum.groupby('Ticker')['CumulativeLogReturn'].transform(lambda x: np.exp(x))

fig_cum_return = px.line(
    df_cum,
    x='Date',
    y='CumulativeReturn',
    color='Ticker',  # Phân biệt các mã bằng màu sắc
    # color_discrete_sequence=px.colors.qualitative.Set2  # Giữ màu giống biểu đồ bar
    color_discrete_map=color_map
)

fig_cum_return.update_layout(
    yaxis_title='Hệ số tăng trưởng',
    xaxis_title='Ngày',
    legend_title='Mã Cổ phiếu',
    plot_bgcolor='white',   # Nền vùng biểu đồ trắng
    paper_bgcolor='white'
)

# 5. Định dạng trục & lưới (giống biểu đồ Close)
fig_cum_return.update_xaxes(
    tickformat="%Y-%m",       # 📅 định dạng 2024-04
    # showline=True,
    # linewidth=2,
    # linecolor='black',
    mirror=True,
    showgrid=True,
    gridwidth=1,
    gridcolor='lightgray'
)
fig_cum_return.update_yaxes(
    tickformat=",.2f",        # 💰 hiển thị 1.25 → 1.25; 10.00 → 10.00
    # showline=True,
    # linewidth=2,
    # linecolor='black',
    mirror=True,
    showgrid=True,
    gridwidth=1,
    gridcolor='lightgray'
)

# 6. Hiển thị
fig_cum_return.show()

# 7. Xuất file ảnh
filename1234 = "CumulativeLogReturn.png"
fig_cum_return.write_image(filename1234)
files.download(filename1234)

print("--- Hoàn thành Biểu đồ Lợi nhuận Tích lũy ---")

# import numpy as np

# print("--- 1. Bắt đầu vẽ Biểu đồ Lợi nhuận Tích lũy ---")

# # 1. Tính lợi nhuận tích lũy cho mỗi mã
# # Dùng LogReturn để cộng dồn (cumsum)
# # (Chúng ta cần reset_index để Ticker và Date trở thành cột)
# df_cum = combined_df.reset_index()

# # Tính LogReturn tích lũy
# df_cum['CumulativeLogReturn'] = df_cum.groupby('Ticker')['LogReturn'].cumsum()

# # 2. Chuyển đổi từ Log Return tích lũy về Return tích lũy
# # (1 đồng đầu tư ban đầu sẽ thành bao nhiêu đồng)
# df_cum['CumulativeReturn'] = (
#     df_cum.groupby('Ticker')['CumulativeLogReturn']
#     .transform(lambda x: np.exp(x))
# )

# # 3. Vẽ bằng Plotly
# fig_cum_return = px.line(df_cum,
#                          x='Date',
#                          y='CumulativeReturn',
#                          color='Ticker', # Phân biệt các mã bằng màu sắc
#                         #  title='So sánh Hiệu suất Đầu tư (Lợi nhuận Tích lũy)'
#                          )
# fig_cum_return.update_layout(yaxis_title='Giá trị (nếu đầu tư 1đ ban đầu)',
#                            xaxis_title='Ngày',
#                            legend_title='Mã Cổ phiếu')
# fig_cum_return.show()

# filename1234 = f"CumulativeLogReturn.png"
# fig_cum_return.write_image(filename1234)
# # files.download(filename1234)

# print("--- Hoàn thành Biểu đồ Lợi nhuận Tích lũy ---")

"""Mục đích: Đây là biểu đồ quan trọng nhất để so sánh hiệu suất đầu tư.

Ý nghĩa: Nó trả lời câu hỏi: "Nếu bạn đầu tư 1 đồng vào mỗi mã (HVN, VJC, ...) vào ngày đầu tiên (01/2024), thì đến hôm nay, mã nào mang lại lợi nhuận cao nhất?"
"""

print("--- 2. Bắt đầu vẽ Biểu đồ Hộp (So sánh Rủi ro) ---")

# Đặt kích thước cho biểu đồ
plt.figure(figsize=(12, 7))

# Sử dụng seaborn để vẽ boxplot
sns.boxplot(data=combined_df,
            x='Ticker',
            y='LogReturn') # Dùng LogReturn để so sánh

# Đặt tiêu đề và nhãn trục
# plt.title('So sánh Phân phối Lợi nhuận (Rủi ro) giữa các Mã', fontsize=16)
plt.xlabel('Mã Cổ phiếu')
plt.ylabel('Lợi nhuận Logarit (LogReturn)')
plt.axhline(0, color='red', linestyle='--', label='Hòa vốn (0)') # Thêm đường 0
plt.legend()
output_path = "boxplot_rui_ro.png"
plt.savefig(output_path, bbox_inches='tight', dpi=300)
plt.show()

files.download(output_path)

print("--- Hoàn thành Biểu đồ Hộp ---")

"""Mục đích: So sánh trực quan độ biến động (rủi ro) của các mã.

Ý nghĩa: Biểu đồ này cho thấy phân phối lợi nhuận hàng ngày.

Hộp (box) càng dài: Mã đó càng biến động, rủi ro càng cao.

Các dấu chấm (outliers): Là những ngày có biến động cực lớn (lãi sốc hoặc lỗ sốc).

Đường ngang ở giữa: Lợi nhuận trung vị (median).
"""

print("--- 4. Bắt đầu vẽ Biểu đồ Biến động Trượt ---")

# 1. Tính toán độ lệch chuẩn trượt (ví dụ cửa sổ 20 ngày)
rolling_vol = (
    combined_df.groupby('Ticker')['LogReturn']
    .rolling(window=20)   # Cửa sổ trượt 20 ngày
    .std()                # Tính độ lệch chuẩn
    .reset_index()
    .rename(columns={'LogReturn':'RollingVolatility'})
)

# 2. Vẽ bằng Plotly
fig_rolling_vol = px.line(
    rolling_vol,
    x='Date',
    y='RollingVolatility',
    color='Ticker',
    # color_discrete_sequence=px.colors.qualitative.Set2  # Giữ màu đồng bộ
    color_discrete_map=color_map
)

# 3. Tùy chỉnh layout
fig_rolling_vol.update_layout(
    plot_bgcolor='white',
    paper_bgcolor='white',
    yaxis_title='Độ lệch chuẩn',
    xaxis_title='Ngày',
    legend_title='Mã Cổ phiếu',
    font=dict(size=13),
    margin=dict(l=60, r=30, t=40, b=50)
)

# 4. Định dạng trục
fig_rolling_vol.update_xaxes(
    tickformat="%Y-%m",  # hiển thị theo dạng 2024-04
    showgrid=True, gridwidth=0.5, gridcolor="LightGray"
)
fig_rolling_vol.update_yaxes(
    tickformat=".2f",    # hiển thị 0.0123 thay vì 0.0123456
    showgrid=True, gridwidth=0.5, gridcolor="LightGray"
)

fig_rolling_vol.show()

filename1234a = "RollingVolatility20.png"
fig_rolling_vol.write_image(filename1234a)
files.download(filename1234a)

print("--- Hoàn thành Biểu đồ Biến động Trượt ---")

# print("--- 4. Bắt đầu vẽ Biểu đồ Biến động Trượt ---")

# # 1. Tính toán độ lệch chuẩn trượt (ví dụ cửa sổ 30 ngày)
# # Dùng groupby('Ticker') để tính rolling cho từng mã
# rolling_vol = (
#     combined_df.groupby('Ticker')['LogReturn']
#     .rolling(window=20)   # Cửa sổ trượt 30 ngày
#     .std()                # Tính độ lệch chuẩn
#     .reset_index()
#     .rename(columns={'LogReturn':'RollingVolatility'})
# )
# # (Chúng ta cần nhân với căn bậc 2 của 252 nếu muốn "năm hóa" (annualize)
# # nhưng để so sánh thì không cần)

# # 2. Vẽ bằng Plotly
# fig_rolling_vol = px.line(rolling_vol,
#                           x='Date',
#                           y='RollingVolatility',
#                           color='Ticker',
#                           # title='Biến động Trượt (30 ngày) - Thước đo Rủi ro theo Thời gian'
#                           )
# fig_rolling_vol.update_layout(yaxis_title='Độ lệch chuẩn (Rủi ro)',
#                             xaxis_title='Ngày',
#                             legend_title='Mã Cổ phiếu')
# fig_rolling_vol.show()

# filename1234a = f"RollingVolatility20.png"
# fig_rolling_vol.write_image(filename1234a)
# files.download(filename1234a)

# print("--- Hoàn thành Biểu đồ Biến động Trượt ---")

print("--- 4. Bắt đầu vẽ Biểu đồ Biến động Trượt ---")

# 1. Tính toán độ lệch chuẩn trượt (ví dụ cửa sổ 20 ngày)
rolling_vol = (
    combined_df.groupby('Ticker')['LogReturn']
    .rolling(window=60)   # Cửa sổ trượt 20 ngày
    .std()                # Tính độ lệch chuẩn
    .reset_index()
    .rename(columns={'LogReturn':'RollingVolatility'})
)

# 2. Vẽ bằng Plotly
fig_rolling_vol = px.line(
    rolling_vol,
    x='Date',
    y='RollingVolatility',
    color='Ticker',
    # color_discrete_sequence=px.colors.qualitative.Set2  # Giữ màu đồng bộ
    color_discrete_map=color_map
)

# 3. Tùy chỉnh layout
fig_rolling_vol.update_layout(
    plot_bgcolor='white',
    paper_bgcolor='white',
    yaxis_title='Độ lệch chuẩn',
    xaxis_title='Ngày',
    legend_title='Mã Cổ phiếu',
    font=dict(size=13),
    margin=dict(l=60, r=30, t=40, b=50)
)

# 4. Định dạng trục
fig_rolling_vol.update_xaxes(
    tickformat="%Y-%m",  # hiển thị theo dạng 2024-04
    showgrid=True, gridwidth=0.5, gridcolor="LightGray"
)
fig_rolling_vol.update_yaxes(
    tickformat=".2f",    # hiển thị 0.0123 thay vì 0.0123456
    showgrid=True, gridwidth=0.5, gridcolor="LightGray"
)

fig_rolling_vol.show()

filename1234a = "RollingVolatility60.png"
fig_rolling_vol.write_image(filename1234a)
files.download(filename1234a)

print("--- Hoàn thành Biểu đồ Biến động Trượt ---")

# print("--- 4. Bắt đầu vẽ Biểu đồ Biến động Trượt ---")

# # 1. Tính toán độ lệch chuẩn trượt (ví dụ cửa sổ 30 ngày)
# # Dùng groupby('Ticker') để tính rolling cho từng mã
# rolling_vol = (
#     combined_df.groupby('Ticker')['LogReturn']
#     .rolling(window=60)   # Cửa sổ trượt 30 ngày
#     .std()                # Tính độ lệch chuẩn
#     .reset_index()
#     .rename(columns={'LogReturn':'RollingVolatility'})
# )
# # (Chúng ta cần nhân với căn bậc 2 của 252 nếu muốn "năm hóa" (annualize)
# # nhưng để so sánh thì không cần)

# # 2. Vẽ bằng Plotly
# fig_rolling_vol = px.line(rolling_vol,
#                           x='Date',
#                           y='RollingVolatility',
#                           color='Ticker',
#                           # title='Biến động Trượt (30 ngày) - Thước đo Rủi ro theo Thời gian'
#                           )
# fig_rolling_vol.update_layout(yaxis_title='Độ lệch chuẩn (Rủi ro)',
#                             xaxis_title='Ngày',
#                             legend_title='Mã Cổ phiếu')
# fig_rolling_vol.show()

# filename1234ab = f"RollingVolatility60.png"
# fig_rolling_vol.write_image(filename1234ab)
# files.download(filename1234ab)

# print("--- Hoàn thành Biểu đồ Biến động Trượt ---")

"""Mục đích: Xem xét sự thay đổi của rủi ro (biến động) theo thời gian.

Ý nghĩa: Giúp bạn xác định các "chế độ thị trường" (market regimes).

Khi đường biểu đồ đi lên: Giai đoạn thị trường "bão tố", rủi ro cao.

Khi đường biểu đồ đi xuống: Giai đoạn thị trường "yên ắng", rủi ro thấp.
"""

# Cài đặt các hằng số cho phân tích
TRADING_DAYS = 252  # Số ngày giao dịch trong 1 năm
RISK_FREE_RATE_ANNUAL = 0.03 # Giả định lãi suất phi rủi ro là 3%/năm

print("--- 1. Bảng tóm tắt số liệu chính (Summary Statistics) ---")

summary_data = []

# Lặp qua từng mã trong dictionary
for ticker, df in stock_data.items():

    # 1. Lợi nhuận trung bình ngày
    mean_daily_return = df['LogReturn'].mean()

    # 2. Lợi nhuận năm hóa
    # (Sử dụng np.exp vì chúng ta dùng LogReturn)
    annualized_return = np.exp(mean_daily_return * TRADING_DAYS) - 1

    # 3. Biến động (rủi ro) năm hóa
    annualized_volatility = df['LogReturn'].std() * np.sqrt(TRADING_DAYS)

    # 4. Tỷ lệ Sharpe
    # (Lợi nhuận năm hóa - Lãi suất phi rủi ro) / Rủi ro năm hóa
    sharpe_ratio = (annualized_return - RISK_FREE_RATE_ANNUAL) / annualized_volatility

    # 5. Mức sụt giảm tối đa (Max Drawdown)
    cum_return_gross = (1 + df['Return']).cumprod() # Dùng Return (không phải Log)
    running_max = cum_return_gross.cummax()
    drawdown = (cum_return_gross - running_max) / running_max
    max_drawdown = drawdown.min()

    # 6. Khối lượng trung bình
    average_volume = df['Volume'].mean()

    # Thêm vào danh sách
    summary_data.append({
        'Ticker': ticker,
        'Mean Daily Return (%)': mean_daily_return * 100,
        'Annualized Return (%)': annualized_return * 100,
        'Annualized Volatility (%)': annualized_volatility * 100,
        'Sharpe Ratio': sharpe_ratio,
        'Max Drawdown (%)': max_drawdown * 100,
        'Average Volume': average_volume
    })

# Tạo DataFrame từ danh sách
summary_df = pd.DataFrame(summary_data).set_index('Ticker')

# In bảng kết quả
# (Sử dụng .T để chuyển vị cho dễ nhìn)
print(summary_df.round(2).T)

"""1. Bảng tóm tắt số liệu chính (Summary Statistics)"""

print("\n--- 5. Phân tích Đột biến Khối lượng (Volume Spike) ---")

df_spike = combined_df.copy().reset_index()

# 1. Tính toán Volume trung bình trượt
df_spike['Volume_MA20'] = (
    df_spike.groupby('Ticker')['Volume']
    .transform(lambda x: x.rolling(window=20).mean())
)

# 2. Định nghĩa ngày "Spike"
df_spike['Is_Spike_Day'] = df_spike['Volume'] > (2.5 * df_spike['Volume_MA20'])

# 3. Vẽ Scatter Plot (cho 1 mã, ví dụ HVN)
ticker_to_plot = 'HVN'
df_spike_single = df_spike[df_spike['Ticker'] == ticker_to_plot]

fig_scatter = px.scatter(df_spike_single,
                         x='Volume',
                         y='Return', # Dùng 'Return' (không phải LogReturn)
                         color='Is_Spike_Day', # Tô màu theo ngày Spike
                        #  title=f'Lợi nhuận vs Khối lượng ({ticker_to_plot})'
                         )
fig_scatter.show()

filename1234ab5 = f"Is_Spike_Day.png"
fig_scatter.write_image(filename1234ab5)
files.download(filename1234ab5)

# 4. Tạo Bảng tóm tắt so sánh
# So sánh |Lợi nhuận| (biến động) vào ngày Spike và ngày thường
df_spike['Abs_Return'] = df_spike['Return'].abs()

spike_summary = (
    df_spike.groupby('Is_Spike_Day')['Abs_Return']
    .mean()
    .to_frame(name='Mean Absolute Return')
)

print("\n--- Bảng tóm tắt Volume Spike ---")
print(spike_summary)

"""Phân tích Đột biến Khối lượng (Volume Spike)

Chúng ta sẽ định nghĩa "spike" là một ngày có khối lượng cao hơn 2 lần so với trung bình 20 ngày.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

print("--- 3. Bắt đầu vẽ Heatmap tương quan và đồng biến động ---")

# Reset index nếu Date đang là index
if 'Date' not in combined_df.columns:
    combined_df = combined_df.reset_index()

# Pivot lại: mỗi cột là 1 mã, mỗi dòng là 1 ngày
returns_pivot = combined_df.pivot(index='Date', columns='Ticker', values='LogReturn')

# --- 3.1. Heatmap tương quan (Full sample) ---
plt.figure(figsize=(8, 6))
corr_matrix = returns_pivot.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0)
# plt.title('Heatmap Tương quan Lợi suất (Full Sample)')
plt.xlabel("")  # Xóa chữ “Ticker”
plt.ylabel("")  # Xóa chữ “Ticker”

output_path = "HeatmapLoiSuat.png"
plt.savefig(output_path, bbox_inches='tight', dpi=300)
plt.show()

files.download(output_path)


# --- 3.2. Heatmap đồng biến động (Full sample) ---
plt.figure(figsize=(8, 6))
cov_matrix = returns_pivot.cov()
sns.heatmap(cov_matrix, annot=True, cmap='viridis')
# plt.title('Heatmap Đồng biến động (Full Sample)')
plt.xlabel("")  # Xóa chữ “Ticker”
plt.ylabel("")  # Xóa chữ “Ticker”

output_path = "HeatmapDongBienDong.png"
plt.savefig(output_path, bbox_inches='tight', dpi=300)
plt.show()

files.download(output_path)
# --- 3.3. Heatmap tương quan Rolling Window ---
window_size = 30  # số ngày cửa sổ trượt
rolling_corr = returns_pivot.rolling(window=window_size).corr()

# Kiểm tra xem có cặp HVN, VJC không
tickers = returns_pivot.columns.tolist()
print("Các mã trong dữ liệu:", tickers)

if 'HVN' in tickers and 'VJC' in tickers:
    # Lấy tương quan rolling giữa HVN và VJC
    hvn_vjc_corr = rolling_corr.xs('HVN', level=1, axis=0)[['VJC']].dropna()

    plt.figure(figsize=(10, 5))
    plt.plot(hvn_vjc_corr.index, hvn_vjc_corr['VJC'], label='HVN - VJC', color='blue')
    plt.title(f'Rolling Correlation ({window_size} ngày) giữa HVN và VJC')
    plt.xlabel('Ngày')
    plt.ylabel('Hệ số tương quan')
    plt.legend()
    plt.show()
else:
    print("⚠️ Không tìm thấy cặp mã HVN và VJC trong dữ liệu!")

print("--- Hoàn thành Heatmap tương quan và đồng biến động ---")

print("--- 4. Phân tích Volume Spike vs Return ---")

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# Đảm bảo có cột Date
if 'Date' not in combined_df.columns:
    combined_df = combined_df.reset_index()

# Xác định Volume trung bình và độ lệch chuẩn theo từng mã cổ phiếu
volume_stats = combined_df.groupby('Ticker')['Volume'].agg(['mean', 'std']).reset_index()

# Gộp thống kê vào dữ liệu gốc
combined_df = combined_df.merge(volume_stats, on='Ticker', how='left', suffixes=('', '_stats'))

# Đánh dấu ngày có "Volume Spike": Volume > mean + 2*std
combined_df['IsSpike'] = combined_df['Volume'] > (combined_df['mean'] + 2 * combined_df['std'])

# --- 4.1. Scatter Plot: Volume vs Return ---
plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=combined_df,
    x='Volume',
    y='Return',
    hue='IsSpike',
    alpha=0.7,
    palette={True: 'red', False: 'blue'}
)
# plt.title('Phân tích Volume Spike vs Return')
plt.xlabel('Khối lượng giao dịch (Volume)')
plt.ylabel('Lợi nhuận (%)')
plt.legend(title='Volume Spike')

output_path = "VolumeSpikeVsReturn.png"
plt.savefig(output_path, bbox_inches='tight', dpi=300)
plt.show()

files.download(output_path)

# --- 4.2. Summary Table: Mean |Return| trên Spike và Non-Spike ---
summary = (
    combined_df.groupby(['Ticker', 'IsSpike'])['Return']
    .apply(lambda x: np.mean(np.abs(x)))
    .reset_index()
    .pivot(index='Ticker', columns='IsSpike', values='Return')
)

summary.columns = ['Mean |Return| (Non-Spike)', 'Mean |Return| (Spike)']
summary['Spike/NonSpike Ratio'] = summary['Mean |Return| (Spike)'] / summary['Mean |Return| (Non-Spike)']
summary = summary.round(4)

print("\n--- Summary Table: So sánh độ biến động giữa ngày Spike và Non-Spike ---")
print(summary)

# --- 4.3. Bar chart minh họa kết quả ---
summary_plot = summary[['Mean |Return| (Non-Spike)', 'Mean |Return| (Spike)']].reset_index()
summary_plot.plot(
    x='Ticker',
    kind='bar',
    figsize=(9, 5),
    # title='So sánh |Return| trung bình: Spike vs Non-Spike',
    xlabel='Mã cổ phiếu',
    ylabel='Giá trị trung bình tuyệt đối của Return',
)
plt.xticks(rotation=0)
plt.tight_layout()

output_path = "SpikeVsNon-Spike.png"
plt.savefig(output_path, bbox_inches='tight', dpi=300)
plt.show()

files.download(output_path)

print("--- Hoàn thành Phân tích Volume Spike vs Return ---")